services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./backend:/app
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      VITE_API_BASE: ${VITE_API_BASE:-http://localhost:8000}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host --port 5173
    ports:
      - "5173:5173"
    depends_on:
      - backend