# Generated by Django 5.2.1 on 2025-10-03 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Precipitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("milimetros", models.FloatField(help_text="Cantidad de lluvia en mm")),
                ("observaciones", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Potrero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("coordenadas", models.JSONField()),
                (
                    "estado",
                    models.CharField(
                        choices=[(0, "Inactivo"), (1, "En descanso"), (2, "Ocupado")],
                        default=0,
                        max_length=10,
                    ),
                ),
                ("area_m2", models.FloatField(default=0)),
                (
                    "pasto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="potreros",
                        to="asistente.pasto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AforoPasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("materia_seca_kg_ha", models.FloatField()),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "potrero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aforos",
                        to="asistente.potrero",
                    ),
                ),
            ],
        ),
    ]
