# Generated by Django 5.2.1 on 2025-10-03 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asistente", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="aforopasto",
            name="potrero",
        ),
        migrations.RemoveField(
            model_name="potrero",
            name="pasto",
        ),
        migrations.DeleteModel(
            name="Precipitacion",
        ),
        migrations.DeleteModel(
            name="AforoPasto",
        ),
        migrations.DeleteModel(
            name="Pasto",
        ),
        migrations.DeleteModel(
            name="Potrero",
        ),
    ]
