# Generated by Django 5.2.1 on 2025-10-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asistente", "0002_perfilusuario_remove_aforopasto_potrero_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfilusuario",
            name="codigo",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
