# Generated by Django 5.2.1 on 2025-10-03 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asistente", "0003_alter_perfilusuario_codigo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PerfilUsuario",
        ),
    ]
