# Generated by Django 5.2.1 on 2025-10-04 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asistente", "0005_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id_producto_pd",
                    models.CharField(max_length=500, primary_key=True, serialize=False),
                ),
                ("ano_convo", models.CharField(blank=True, default="", max_length=500)),
                (
                    "cod_grupo_gr",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "fcreacion_pd",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "id_convocatoria",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "id_persona_pd",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "id_tipo_pd_med",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "nme_categoria_pd",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "nme_clase_pd",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "nme_convocatoria",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "nme_grupo_gr",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "nme_producto_pd",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                (
                    "nme_tipo_medicion_pd",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "nme_tipologia_pd",
                    models.CharField(blank=True, default="", max_length=500),
                ),
            ],
            options={
                "db_table": "Productos",
            },
        ),
        migrations.AlterField(
            model_name="codigousuario",
            name="codigo",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="codigousuario",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="codigo_usuario",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
