# Generated by Django 5.2.1 on 2025-10-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asistente", "0006_producto_alter_codigousuario_codigo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="producto",
            name="id_producto_pd",
            field=models.CharField(max_length=500),
        ),
    ]
