# Generated by Django 5.2.1 on 2025-10-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asistente", "0007_producto_id_alter_producto_id_producto_pd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="ano_convo",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="cod_grupo_gr",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="fcreacion_pd",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="id_convocatoria",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="id_persona_pd",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="id_producto_pd",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="id_tipo_pd_med",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nme_categoria_pd",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nme_clase_pd",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nme_convocatoria",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nme_grupo_gr",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nme_producto_pd",
            field=models.CharField(blank=True, default="", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nme_tipo_medicion_pd",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nme_tipologia_pd",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
    ]
